// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_vLP_AYLa6_5BQ4z8YIPcy1y_zoIweUk',
    appId: '1:108197983780:android:48a44e93f08512e2a88ab1',
    messagingSenderId: '108197983780',
    projectId: 'antrian-rumah-sakit-pmo',
    databaseURL: 'https://antrian-rumah-sakit-pmo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'antrian-rumah-sakit-pmo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT5kdseqlHW_aWKumb_QSKN3JWVA0AWNg',
    appId: '1:108197983780:ios:f462f048f4b4aa4ca88ab1',
    messagingSenderId: '108197983780',
    projectId: 'antrian-rumah-sakit-pmo',
    databaseURL: 'https://antrian-rumah-sakit-pmo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'antrian-rumah-sakit-pmo.appspot.com',
    iosBundleId: 'com.minimal.antiranRumahSakit',
  );

}